# BASE_PATH  = '/gdrive/MyDrive/deep-learning/final-project/data-sets/'
BASE_PATH = 'data-sets/'
ORIGINAL_IMAGES = BASE_PATH + "0_Images/"
ROTATED_IMAGES = BASE_PATH + "1_ImagesRotated/"
MEDIAN_BW_IMAGES = BASE_PATH + "2_ImagesMedianBW/"
LINES_REMOVED_BW_IMAGES = BASE_PATH + "3_ImagesLinesRemovedBW/"
LINES_REMOVED_IMAGES = BASE_PATH + "4_ImagesLinesRemoved/"
DARK_LINES = BASE_PATH + "5_DataDarkLines/"
SAMPLE_FILE_PATTERN = "lines{}_Page_{}.jpg"
METADATA_PATTERN = "lines{}_Page_{}.mat"
MODEL_CHECKPOINT_PATH = BASE_PATH + "model_checkpoints/"
SUB_IMAGES_PATH = BASE_PATH + "sub_images/"

ALLOWED_TYPES = [ORIGINAL_IMAGES, ROTATED_IMAGES, MEDIAN_BW_IMAGES, LINES_REMOVED_BW_IMAGES, LINES_REMOVED_IMAGES]
TRAIN_TYPES = [ROTATED_IMAGES,  LINES_REMOVED_BW_IMAGES]
VALIDATE_TYPES = [ORIGINAL_IMAGES]
EMBEDDING_TYPES = [ORIGINAL_IMAGES, LINES_REMOVED_BW_IMAGES]
CLASSIFICATION_TYPES = [ORIGINAL_IMAGES, LINES_REMOVED_BW_IMAGES, LINES_REMOVED_IMAGES]
LINE_SHAPE = (225, 4965)


MODE_TRAIN = 'train'
MODE_VALIDATION = 'validation'
MODE_TEST = 'test'

